eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://13.126.171.28:8761/eureka
okta:
  oauth2:
    issuer: https://dev-49846363.okta.com/oauth2/default
    audience: api://default
